### ISSUE TITLE
Set aspect ratio to 'equal' 

### ISSUE THREAD

**Issue by abast** [flekschas/jupyter-scatter#104]
I would like to ensure that the  x and y axis are scaled such that data is shown with equal aspect ratio (similar to matplotlib: `ax.set_aspect('equal')`. I thought of using the `width()` and `height()` function to figure out the dimensions of the scatter widget and use that for scaling. However, `width()` return auto, and I am not sure I am on the right track.

**Comment by flekschas** [comment]
By default the aspect ratio is 1:1. So the x and y axes should be scaled equally. If you must you can override this behavior using the aspectRatio setting of regl-scatterplot that you can set via Scatter(options={'aspectRatio': 2.0})

(Typing this on my phone and haven't tested it yet, so there might be a typo 😬)

**Comment by flekschas** [comment]
I can confirm: by default the aspect ratio is 1. E.g.:

![Screenshot 2024-01-17 at 8 38 40 PM](https://github.com/flekschas/jupyter-scatter/assets/932103/5fdae0eb-2e88-4bdb-93e3-b2ed79f573aa)

However, I noticed there's a bug regarding the options. To change the aspect ration, you have to do the following work around:

```py
import jscatter
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "x": np.concatenate((np.linspace(start=-10, stop=10, num=50), np.linspace(start=-10, stop=10, num=50))),
    "y": np.concatenate((np.linspace(start=-10, stop=10, num=50), np.linspace(start=10, stop=-10, num=50))),
})

scatter = jscatter.Scatter(data=df, x="x", y="y")
scatter.widget.other_options = {"aspectRatio": 2}
scatter.show()
```

![Screenshot 2024-01-17 at 8 48 30 PM](https://github.com/flekschas/jupyter-scatter/assets/932103/a25c440b-70f0-4f27-9565-b265f998ee1f)

Does this help?

**Comment by flekschas** [comment]
I'm closing this ticket as both issue (setting an aspect ratio) and custom ranges are fixed via #109. The fixes will go out with the next release (v0.15.0)

If you want to render both axes at the same range you can now do

```py
import jscatter
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "x": np.concatenate((np.linspace(start=-10, stop=10, num=15), np.linspace(start=-10, stop=10, num=15))),
    "y": np.concatenate((np.linspace(start=-1, stop=5, num=15), np.linspace(start=1, stop=-1, num=15))),
})

common_scale = (df[['x', 'y']].min().min(), df[['x', 'y']].max().max())

scatter = jscatter.Scatter(
    data=df,
    x="x",
    y="y",
    x_scale=common_scale,
    y_scale=common_scale,
)
scatter.show()
```

![Screenshot 2024-02-01 at 9 31 28 AM](https://github.com/flekschas/jupyter-scatter/assets/932103/1c5f5aa6-725b-45da-99c3-6f34c2b07399)


If you still have questions or the fixes don't work, feel free to reopen the issue.

**Comment by flekschas** [comment]
The terminology might be ambiguous here as aspect ratio is a view property of regl-scatterplot and refers to the aspect ratio of the normalized decide coordinate space and _not_ the data space. So yeah, maybe one can say the aspect ratio is one w.r.t. to the data bounds.

Or in other words, X ([1, 3]) is plotted across (say) 100px and Y ([100, 300]) is also plotted across 100px.

**Comment by abast** [comment]
Thanks for the explanation!

**Comment by abast** [comment]
Hm, so what do I need to do to get equal aspect in data space? Provide a common_scale for x and y? Is it ok to provide a scale that is smaller than min() and max(), e.g. (0,1)? If I need to use min() and max(), what happens if I update the data to something larger that is beyond the old min and max?

I wish there were commands similar to matplotlib, which all refer to the data space:
`ax.set_xlim(xmin,xmax)`
`ax.set_ylim(ymin,ymax)`
`ax.set_aspect('equal')`

**Comment by flekschas** [comment]
> I wish there were commands similar to matplotlib, which all refer to the data space:
> `ax.set_xlim(xmin,xmax)`
> `ax.set_ylim(ymin,ymax)`
> `ax.set_aspect('equal')`

There is:
- `scatter.x(scale=(xmin, xmax))`
- `scatter.y(scale=(ymin, ymax))`
- Given `aspect = (xmax - xmin) / (ymax - ymin)`: `scatter.width(100).height(100 / aspect).options({"aspectRatio": aspect})`

---

E.g.:

Given

```py
import numpy as np

x = np.random.rand(750) * 20
y = np.random.rand(750)

xmin, xmax = (2, 8)
ymin, ymax = (-1, 2)
```

In Maptplitlob

```py
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

ax.scatter(x, y, c='black', alpha=0.3, edgecolors='none')

ax.set_xlim(xmin, xmax)
ax.set_ylim(ymin, ymax)
ax.set_aspect("equal")

plt.show()
```

![Screenshot 2024-06-16 at 8 40 05 PM](https://github.com/flekschas/jupyter-scatter/assets/932103/18fe43a8-9002-483c-9f7e-075d48904e08)

And in JScatter:

```py
import jscatter

data_aspect = (xmax - xmin) / (ymax - ymin)

scatter = jscatter.Scatter(
    x=x,
    x_scale=(xmin, xmax),
    y=y,
    y_scale=(ymin, ymax),
    width=400,
    height=400 / data_aspect,
    size=5,
    options = {"aspectRatio": data_aspect}
)
scatter.show()
```

![Screenshot 2024-06-16 at 8 40 12 PM](https://github.com/flekschas/jupyter-scatter/assets/932103/5ebd12cc-7879-4a31-8d43-0a8905268ff4)

I agree that it'd be nice to have a convenience function like `set_aspect()`. If you want to take a stab at implementing it, I'm happy to merge the feature!

**Comment by abast** [comment]
Thanks for this example and sorry for taking a while to respond. 

While your code displays the data with equal aspect initially, once one axis is changed, equal aspect is lost (just run scatter.y(x) ... if equal aspect is maintained that should be a line at 45 degree angle, which it is not). Here is an illustration:

<img width="483" alt="image" src="https://github.com/flekschas/jupyter-scatter/assets/20513804/2ecc5272-47e2-42a5-8b01-54374f660d46">

Let me give some context of why this matters to me. I want to visualize neural recordings of thousands of neurons, each neuron having various properties (let's say firing rates, stimuli at which it responds etc.), as well as a spatial position. Which properties are shown on which axis is something the user can pick from a dropdown menu. jscatter in its current form works great for the properties that are of different units, where essentially all I want is to display them in a way that fully utilizes the axis. But when I want to display the spatial position of the cells (both having the unit micrometer, in x and y), then I want to make sure they are displayed in equal aspect. Currently I am not sure how to ensure equal aspect after a number of calls of scatter.x(), scatter.y(), scatter.data().
