### ISSUE TITLE
broken link in docstring

### ISSUE THREAD

**Issue by chanana** [flekschas/jupyter-scatter#110]
https://github.com/flekschas/jupyter-scatter/blob/main/jscatter/jscatter.py#L148 link leads to nowhere

**Comment by chanana** [comment]
should probably lead to https://github.com/flekschas/jupyter-scatter/blob/main/docs/api.md#properties

**Comment by flekschas** [comment]
Good find! Ideally it links to the website (https://jupyter-scatter.dev/api) which renders out the API nicer. I'll fix the link.

**Comment by flekschas** [comment]
Will be fixed as part of #109
