### ISSUE TITLE
Failed to load model class 'AnyModel' from module 'anywidget'

### ISSUE THREAD

**Issue by drorbar** [flekschas/jupyter-scatter#113]
Hi,

Tried to work with the library using the sample example in the tutorial.
I'm getting the following error:
![image](https://github.com/flekschas/jupyter-scatter/assets/6944785/a91b4d59-02be-451a-be37-d025b771e68d)

I'm using anywidged=='0.9.3'
the problem seems to happen in jupyter notebook and not in jupyter lab 

Thanks

**Comment by flekschas** [comment]
Thanks for reporting the bug. @manzt Any idea what the issue might be with anywidget here?

**Comment by manzt** [comment]
I am not able to reproduce.

```sh
python3 -m venv .venv
source .venv/bin/activate
pip install notebook==7.1.2 jupyter-scatter=0.15.0
jupyter notebook
```

```py
import jscatter
import numpy as np

x = np.random.rand(500)
y = np.random.rand(500)

jscatter.plot(x, y)
```

<img alt="jupyter scatter in classic jupyter notebook" src="https://github.com/flekschas/jupyter-scatter/assets/24403730/7619a7c4-5a1e-4142-9986-d878d25cda4c">


This kind of error message usually pops up if you install anywidget for the first time into a _running_ jupyter session (e.g., via `%pip install jupyter-scatter` or `!pip install jupyter-scatter`). You must have anywidget in your environment _before_ starting the jupyter (not just restarting the kernel).

**Comment by drorbar** [comment]
Can confirm that this was the problem,
Thank you very much
