### ISSUE TITLE
Using symbols other than circles in scatter plot

### ISSUE THREAD

**Issue by mbignotti** [flekschas/jupyter-scatter#114]
You have an idea how to enhance Jupyter Scatter? That's awesome!

Before you file your idea, please:

- [x] Check for duplicate issues.
- [x] Describe the feature's goal, motivating use cases, its expected behavior, and impact.
- [x] If you are proposing a new API, please explain how the current APIs fail to support your goal.
- [x] If you are proposing to change an existing API, please explain if your proposed is backward compatible or incompatible.
- [x] If applicable, include screenshots, GIFs, videos, or working examples.

You are encouraged to prototype multiple alternative APIs or implementation approaches for your proposed feature. Doing so often leads to a better solution.

Hi!
Thanks a lot for this great widget!
I wanted to as whether it's currently possible to use different symbols in the scatter plot based on the values of a column of the dataframe or not. A bit like the `symbol` option in plotly (https://plotly.com/python-api-reference/generated/plotly.express.scatter.html). 

I couldn't find anything in the documentation, hence I'm wondering whether there's some workaround or the feature simply does not exist at the moment.

Thanks!

**Comment by flekschas** [comment]
Unfortunately this feature doesn't exist at the moment and it's likely not going to happen any time soon as the underlying plotting library (regl-scatterplot) optimizes for speed and scalability. It therefore doesn't support plotting anything other than round (or square) points.

The reason behind this is when you have tens of thousands or even millions of points, each point is so small that shape differences won't be perceivable. On top of that, drawing points with WebGL scales further as far as I know.

Having said that, I know that there are many valid use cases where different shape come in handy. So it's not impossible that in the future you can pick and choose the point shape (or even define your own)

**Comment by mbignotti** [comment]
Got it!
Thank you!
