### ISSUE TITLE
AttributeError: 'JupyterScatter' object has no attribute 'hovered_point'

### ISSUE THREAD

**Issue by InquilineKea** [flekschas/jupyter-scatter#115]
When I pip install jscatter and then cd into the directory and jupyter lab, and then run the code
``import jscatter
import numpy as np

x = np.random.rand(500)
y = np.random.rand(500)

jscatter.plot(x, y)

I get the error "JupyterScatter' object has no attribute 'hovered_point' #115"
same issue on https://colab.research.google.com/drive/195z6h6LsYpC25IIB3fSZIVUbqVlhtnQo?usp=sharing#scrollTo=fhBnK0fHzIe6

**Comment by michaelfekadu** [comment]
I had the same issue. Downgrading anywidget solved the problem for me. Try to uninstall anywidget and run:
'pip install anywidget==0.9.3 '

**Comment by InquilineKea** [comment]
I get this new strange issue: "FileNotFoundError: File not found: /Users/simfish/Documents/GitHub/jupyter-scatter/jscatter/bundle.js
"
