### ISSUE TITLE
ERROR: Could not build wheels for jscatter, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by InquilineKea** [flekschas/jupyter-scatter#116]
When I pip install jscatter on my terminal I get this error

EdIT: found a way out of it [for now]

**Comment by manzt** [comment]
Going to close because you found a solution! I think this arises with an old version of Python/setuptools and is likely not specific to jupyter-scatter. If you run into the issue again, please feel free to reopen with more information!
