### ISSUE TITLE
Is there anyway for me to get this out of a jupyter notebook (at least a bit) 

### ISSUE THREAD

**Issue by GeorgePearse** [flekschas/jupyter-scatter#124]
I want to hand this over to non-technical users, and stitch it together with a few python workflows. 

What's my best option for this? Should I try to productionise the jupyter notebook as a web app? 

Could I embed it in anything else?

**Comment by flekschas** [comment]
I think it depends a bit on what you're trying to accomplish.

Jupyter Scatter uses [regl-scatterplot](https://github.com/flekschas/regl-scatterplot) under the hood (you could almost go as far an call Jupyter Scatter just an API layer for integration with the Jupyter and Pandas world) so it's definitely possible to replicate the interface in a web app. However, this requires fully understanding regl-scatterplot's API (which isn't the most intuitive I must confess 😅).

A more lightweight option would be [voila](https://voila.readthedocs.io/en/stable/using.html) (streamlit is unfortunately not an option as [it does not support ipywidgets](https://github.com/flekschas/jupyter-scatter/issues/83)). I personally haven't used voila before but in a quick test it seems to render the notebook with jscatter just fine.

You can also use nbconvert to turn your notebook into a sharable HTML page if you don't need to run any computation interactively. For now just keep in mind of the [selection limitation when using nbconvert](https://github.com/flekschas/jupyter-scatter/issues/82).

@manzt Do you by chance know of other cool libraries for turning a notebook into a deployable web app?

**Comment by GeorgePearse** [comment]
This is great answer @flekschas really appreciate it. 

Had just started looking into whether voila would do the trick.

**Comment by GeorgePearse** [comment]
Getting it running with voila was pretty incredibly easy.

![image](https://github.com/flekschas/jupyter-scatter/assets/47161914/5950c69b-ca75-4265-a306-93209c255c51)

**Comment by manzt** [comment]
> @manzt Do you by chance know of other cool libraries for turning a notebook into a deployable web app?

There are a couple dashboarding frameworks with support for widgets. I haven't built anything that substantial with any.

- https://github.com/holoviz/panel
- https://github.com/widgetti/solara
- https://github.com/posit-dev/py-shiny

I believe solara is the most oriented around widgets (cc: @maartenbreddels)

**Comment by flekschas** [comment]
Wow nice! Thanks for sharing the snippets!

@GeorgePearse Does that help you getting started?

**Comment by GeorgePearse** [comment]
@flekschas got a silly number of good options now, tooling in this space has got so much better over the last few years.

**Comment by flekschas** [comment]
Awesome! I'll close the ticket then but please feel free to reopen it if you have more questions.
