### ISSUE TITLE
axes tick labels are not updated after changing x or y

### ISSUE THREAD

**Issue by abast** [flekschas/jupyter-scatter#127]
```
jscatter.__version__ 
>'0.15.1'
```

```
# create data frame with 3 columns that require different scaling
df = pd.DataFrame([[1,2,3],[1,2,3],[10,20,100]], index = ['a', 'b', 'c']).T
# initial scatter plot is rendered correctly
s = Scatter(data = df, x = 'a', y = 'b')
s.show()
```

initial scatter plot is rendered correctly
<img width="978" alt="image" src="https://github.com/flekschas/jupyter-scatter/assets/20513804/dceab50f-e786-43d8-ad6a-b8989b41cae0">

Afterwards, change x to column c. This does not update the axis, resulting in an incorrect plot:
```
s.x('c')
```

After changing x to column c, the xticks are not updated and are incorrect. 
<img width="970" alt="image" src="https://github.com/flekschas/jupyter-scatter/assets/20513804/732e4fbf-5857-41e0-ad81-dda3225da4ad">

**Comment by flekschas** [comment]
Already fixed in #125 :)

**Comment by flekschas** [comment]
But thanks a lot for reporting! 🙏   I'll merge the bug fix PR today and should be able to cut a release with the fixes soon.

**Comment by abast** [comment]
Fantastic!

**Comment by abast** [comment]
This is fixed, right?

**Comment by flekschas** [comment]
I think so
