### ISSUE TITLE
axvline and axhline

### ISSUE THREAD

**Issue by abast** [flekschas/jupyter-scatter#128]
Is there a possibility to show horizontal or vertical (non-selectable) lines in the plot, similar to matplotlibs axvline and axhline?

**Comment by flekschas** [comment]
Unfortunately such a feature is not available yet.

The closest thing you can get is drawing grid lines where the axis ticks are. While not the same as a dedicated x/y line the grid lines redraw as you zoom in and should help locating points. You can activate them via `scatter.axes(grid=True)`
