### ISSUE TITLE
animations not working after version 0.16.1

### ISSUE THREAD

**Issue by abast** [flekschas/jupyter-scatter#153]
```
import jscatter
import numpy as np
import pandas as pd

data1 = pd.DataFrame({
    "x": np.random.rand(1000),
    "y": np.random.rand(1000),
    "z": np.random.rand(1000),
})
data2 = pd.DataFrame({
    "x": 2*np.random.rand(1000),
    "y": 2*np.random.rand(1000),
    "z": np.random.rand(1000),
})
scatter = jscatter.Scatter(data=data1, x="x", y="y", width=500, height=500)
scatter.show()
```

Changing the column was animated previously (up to 0.16.1), but is not anymore:
`scatter.x('z')
`

How can I get the old behavior?

**Comment by flekschas** [comment]
Thanks for reporting this bug. Please see and test https://github.com/flekschas/jupyter-scatter/pull/155 for a fix.

**Comment by abast** [comment]
Awesome, thanks for your fast response! I'll be traveling the  coming week, so I can test it once I am back.
