### ISSUE TITLE
sync_view applies x/y ticks to all plots

### ISSUE THREAD

**Issue by abast** [flekschas/jupyter-scatter#158]
```
import jscatter
import numpy as np
import pandas as pd

data1 = pd.DataFrame({
    "x": np.random.rand(1000),
    "y": np.random.rand(1000),
})
data2 = pd.DataFrame({
    "x": 200*np.random.rand(1000),
    "y": 200*np.random.rand(1000),
})
s0 = jscatter.Scatter(data=data1, x="x", y="y", width=500, height=500)
s1 = jscatter.Scatter(data=data2, x="x", y="y", width=500, height=500)
compose(
    [s0, s1],
    sync_view = True
)
```

Hover your mouse over s0, zoom in and out, hover your mouse over s1, zoom in and out. Note the change in axis tick labels, which are wrongfully applied to all plots. 

Here is a video: 

https://github.com/user-attachments/assets/e1b69906-9f41-424e-8357-1d4256a7fcc1

For me, axis displaying an incorrect range is one of the main types of 'anxiety' I have when using jscatter (which has become an integral tool for me for interactively exploring my data, an I absolutely love it!). I am often suspicious something might be wrong, so I replot in matplotlib, just to be sure. I am not sure how feasible this is - but are there places where some assert statements could be placed to make sure the labels are correct? E.g. the xtick label just left of the datapoint with the highest x-value must have a smaller numerical value than the x-value of that datapoint.

**Comment by flekschas** [comment]
Thanks for reporting the issue. I think I know what the source issue is.

And I agree, we need to add many more tests to Jupyter Scatter to better catch these issues. Being an interactive widget is making this a bit more tricky as we not only need Python but also JavaScript tests. I welcome any help writing those tests if you want to take a stab at them.

**Comment by flekschas** [comment]
@abast If you have a chance, can you test https://github.com/flekschas/jupyter-scatter/pull/161?

**Comment by abast** [comment]
Yes, I can come back to this tomorrow

**Comment by abast** [comment]
Yes, my college Jody Clements (https://github.com/neomorphic) has tested it and it works! Thanks!

(I meant to put that comment here, but by mistake put it here: https://github.com/flekschas/jupyter-scatter/issues/159)
