### ISSUE TITLE
Widget crashes when doing the selection in VSCode

### ISSUE THREAD

**Issue by iamyihwa** [flekschas/jupyter-scatter#165]
Hello, 
Thanks a lot for the great tool! 

I have just started using it, and I've noticed whenever i do hover selection the tool crashes. 
I was testing one example from the documentation page. All work well, until I do the hover selection, then it crashes. 
I am using Microsoft Visual Studio Code. The version of jscatter i am using is '0.18.1' .  

<img width="778" alt="image" src="https://github.com/user-attachments/assets/c14b38d7-c274-4789-a995-6d517f1e7139">

No error message is given when it crashes, but the notebook simply crashes.
Tested with multiple examples, but always the same crashing with the hover selection.

**Comment by iamyihwa** [comment]
The same crashing happens, also with [this example](https://jupyter-scatter.dev/selections#get-interactive) , whenever there needs to be some interaction happening, it crashes.

**Comment by flekschas** [comment]
Which version of VSCode are you using? And have you tried Jupyter Scatter v0.19.0?

I just tried to reproduce the issue in Jupyter Lab and everything works as expected.

https://github.com/user-attachments/assets/3de60484-020e-456a-b961-0ab667c4c927

**Comment by flekschas** [comment]
Selections and hover also work as expected in VSCode (v1.92.2) for me with Jupyter Scatter v0.19.0.

https://github.com/user-attachments/assets/f1efa952-78cd-49d1-9f39-2578ecd4473e

Did you check the developer console for errors? (`SHIFT + CMD + P` then search for `Developer: Toggle Developer Tools`. This will open a console which might an error message)

**Comment by flekschas** [comment]
Perfect! I'm glad this was an easy fix :)
