### ISSUE TITLE
how to fix the x axis and y axis range

### ISSUE THREAD

**Issue by jacowp357** [flekschas/jupyter-scatter#171]
How can the x-axis and y-axis ranges be set?

For example, in Matplotlib it is: 

plt.xlim(1, 5)

**Comment by flekschas** [comment]
Have you tried `Scatter(data=df, x='x', x_scale=(-10, 10), y='y', y_scale=(42, 1337))`?

**Comment by flekschas** [comment]
Closing this ticket as I assume your question is answered. If it's not feel free to reply/reopen.
