### ISSUE TITLE
Disable pan / zoom

### ISSUE THREAD

**Issue by mjohnson11** [flekschas/jupyter-scatter#176]
I'm wondering if there is a way to make the regl-scatterplot camera fixed. I found https://github.com/flekschas/regl-scatterplot/issues/94, but wondering if there is any workaround to set this from the python side?

**Comment by flekschas** [comment]
Unfortunately, I don't think that's possible from Python yet. Shouldn't be hard to add but I'm curious, what's your use case?

**Comment by mjohnson11** [comment]
Essentially just my preference! I find myself often trying to scroll down and accidentally zooming out on the plot a lot.

**Comment by flekschas** [comment]
I see, that makes sense. I could expose a property to allow fixing the camera via `scatter.camera(fixed=True)`.

**Comment by flekschas** [comment]
I implemented camera fixing via `scatter.camera(is_fixed=True)` in https://github.com/flekschas/jupyter-scatter/pull/179. Let me know if this is what you had in mind.

**Comment by mjohnson11** [comment]
Demo looks perfect!
