### ISSUE TITLE
Callbacks from composed plots

### ISSUE THREAD

**Issue by mjohnson11** [flekschas/jupyter-scatter#177]
I could be missing a way to do this already, but I think it isn't possible to observe all of the plots in a composed set of plots without accidentally observing the changes caused by synced selection or hovering. The use case here is observing what is happening in the linked plots and then reflecting that in another widget (and caring about which plot is being hovered on or selected on). I was able to get this working by redefining compose and adding just a few lines:

- Options to provide callback functions select_callback and hover_callback
- Callbacks in the middle of the unobserve-reobserve sections of code, e.g. for selection:
```python
                # Unsubscribe to avoid cyclic updates
                scatter.widget.unobserve(scatter_select_handlers[i], names='selection')

                if select_callback:
                    select_callback(change)
                if change['new'] is None:
                    scatter.widget.selection = []
                elif match_by == 'index':
                    scatter.widget.selection = matched_ids
                else:
                    scatter.widget.selection = match_mapper(scatter, matched_ids)

                # Re-subscribe to listen to changes coming from the JS kernel
                scatter.widget.observe(scatter_select_handlers[i], names='selection')
```

Does this make sense as a way to implement this?

As I said in my other comment, I am a bit of a github collaboration novice, but I would be happy to make a pull request if you're willing to bear with me on learning the process.

**Comment by flekschas** [comment]
Just so I understand you correctly, you have a grid of `scatter` instances whose selection and hover state is linked/synchronize. Now you want to observe selection and hover changes for those scatter plots and you want to know which scatter plot was the origin of the selection/hover change?

I believe you can achieve this without any changes to jscatter.

```py
import dataclasses
import jscatter
import numpy as np

x, y = np.random.rand(500), np.random.rand(500)
a, b = jscatter.Scatter(x=x, y=y), jscatter.Scatter(x=x, y=y)

@dataclasses.dataclass
class Selection:
    """Class for keeping track of the selection."""
    points: np.ndarray
    source: str

selection = Selection(np.empty(0), "")

def create_selection_handler(source, selection):
    def selection_hander(change):
        if not np.array_equal(selection.points, change["new"]):
            selection.points = change["new"]
            selection.source = source
            print(f"Selection was changed by {source} to {change["new"]}")
    return selection_hander

a.widget.observe(create_selection_handler("a", selection), names=["selection"])
b.widget.observe(create_selection_handler("b", selection), names=["selection"])

jscatter.compose([a, b], sync_selection=True, sync_hover=True)
```

Does this help you accomplish what you're looking for?

**Comment by mjohnson11** [comment]
Oh nice, yes this works! The only difference I can think of is whether it is more efficient to unobserve and reobserve vs. sending more observe calls (if that's the right way to think about it). But this 100% works for me, thanks! And thanks for making this tool!

**Comment by flekschas** [comment]
Thanks for asking about it. I never tested the above scenario before but I'm glad I did now. :)

I don't think the additional observers cause any performance issues but if they do, please reopen this issue we can explore you initial proposal.
