### ISSUE TITLE
Plots won't display when using jupyter notebook in vscode

### ISSUE THREAD

**Issue by clkruse** [flekschas/jupyter-scatter#37]
I use VSCode when developing and running jupyter notebooks. However, I'm not able to get jupyter-scatter plots to display here. They do work when running a jupyter notebook in the browser. I have not tested jupyterlab functionality.

Here's a small reproducible test case:
```
from IPython.display import display
import jscatter
import numpy as np

x = np.random.randn(100)
y = np.random.randn(100)
fig = jscatter.Scatter(x, y)
fig.show()
```
This will return an empty cell. When printing the `fig` variable, it seems to have been created properly, but does not display. `print(fig.show())` produces:
```
HBox(children=(VBox(children=(Button(button_style='primary', icon='arrows', layout=Layout(width='36px'), style=ButtonStyle(), tooltip='Activate pan & zoom'), Button(icon='....
```

To verify that ipywidgets still work, I made and displayed the following simple widget. This worked as expected.
```
import ipywidgets
out = ipywidgets.Dropdown(options=['1', '2', '3'], value='2', description='Number')
display(out)
```

**Comment by flekschas** [comment]
Thank you for reporting the issue. Unfortunately, I'm not a VSCode user and have only tested the plugin in Jupyter Notebook and Lab. My hunch is that VSCode is running the notebooks slightly differently and that's maybe why nothing appears.

Does VSCode have a console of some sort where errors are logged? It's hard to tell without any error message what might cause the issue.

**Comment by clkruse** [comment]
An abbreviated version of what I'm seeing in the VSCode dev tools menu looks like this:

```
Failed to to Widget load class jupyter-scatterJupyterScatterModel
{className: 'JupyterScatterModel', moduleName: 'jupyter-scatter', moduleVersion: '0.7.1', error: Error: Module jupyter-scatter, semver range 0.7.1 is not registered as a widget module

ipywidgets.js:2 Uncaught (in promise) Error: Module jupyter-scatter, semver range 0.7.1 is not registered as a widget module
    at vC.loadClass (ipywidgets.js:2:3955035)
    at vC.loadClass (ipywidgets.js:2:4214431)
    at vC.<anonymous> (ipywidgets.js:2:3553770)
    at ipywidgets.js:2:3550482
    at Object.next (ipywidgets.js:2:3550587)
    at ipywidgets.js:2:3549523
    at new Promise (<anonymous>)
    at j (ipywidgets.js:2:3549268)
    at e._make_model (ipywidgets.js:2:3553649)
    at vC.<anonymous> (ipywidgets.js:2:3553503)
```

**Comment by flekschas** [comment]
Oh that mean that the widget wasn't installed/registered properly. I.e., what the error is saying that the Python widget v0.7.1 is not finding a corresponding front-end widget with v0.7.1.

How did you install jupyter-widget for VSCode? (Sorry this might be a dump question but I'm a SublimeText user)

**Comment by flekschas** [comment]
I tried to get jupyter-scatter to run with VS Code the other day and can confirm that, while ipywidgets work, jupyter-scatter does not work. At this point I am not sure though what causes the issue but I suspect that jupyter-scatter might be incompatible for some unknown reason with VS Codes ipywidget helper.

**Comment by manzt** [comment]
It seems jupyter-scatter just stopped working in VS Code. Different from this original issue, but re-opening to make it easier to track/find. Some kind of regl error. 

To reproduce:

```sh
python -m venv .venv
source .venv/bin/activate
pip install jupyter jupyter-scatter
code . # open VS Code
```

In VS Code, `Shift-Command-P` > `Create Jupyter Notebook`

```py
import jscatter
import numpy as np

x = np.random.rand(500)
y = np.random.rand(500)

jscatter.plot(x, y)
```

Browser console:

```
WebGL: INVALID_VALUE: texImage2D: width or height out of range
    resize @ 0d64b545-9952-417f-9798-c0c13210ef8a:3096

Uncaught Error: (regl) invalid renderbuffer size
    at raise2 (0d64b545-9952-417f-9798-c0c13210ef8a:56:21)
    at check (0d64b545-9952-417f-9798-c0c13210ef8a:62:11)
    at Function.resize (0d64b545-9952-417f-9798-c0c13210ef8a:3555:13)
    at resizeAttachment (0d64b545-9952-417f-9798-c0c13210ef8a:3819:39)
    at Function.resize (0d64b545-9952-417f-9798-c0c13210ef8a:4186:13)
    at resize (0d64b545-9952-417f-9798-c0c13210ef8a:11834:9)
```

cc @simonwarchol pinged me yesterday to let me know.

**Comment by simonwarchol** [comment]
Thanks for beating me to making an issue 🙂

**Comment by flekschas** [comment]
Thanks for reporting! I suspect that either the width, height, or both are zero for a split second or that this is some kind of race condition during the initial rendering. Either way it sounds like a regl-scatterplot bug.

I don't know when I'll get to due to my parental leave, so please go ahead and investigate if you have some time. But I'll try to look once I have the chance.

**Comment by flekschas** [comment]
This is wild... somehow when VSCode executes the cell, the screen width and height is reported to be `1290` and `22144` respectively. The height is obviously nonsense and the cause for the error as I don't think one can even have a frame buffer with such an extreme height. Not sure what's going on with VSCode here but it likely sounds like a bug on their end... I'll investigate but can't promise I'll find a solution.

**Comment by jakobtroidl** [comment]
update: for some reason, jscatter renders with no error on my extended display (DELL U2417H at 1080p default resolution) when using vscode. if i drag the vscode window to my built in mac pro display I get the error message we saw already (attached below). 

``` javascript
Error: (regl) invalid renderbuffer size
    at raise2 (513aadcd-bf36-4115-b…-8beaaa79b87b:56:21)
    at check (513aadcd-bf36-4115-b…-8beaaa79b87b:62:11)
    at Function.resize (513aadcd-bf36-4115-b…beaaa79b87b:3555:13)
    at resizeAttachment (513aadcd-bf36-4115-b…beaaa79b87b:3819:39)
    at Function.resize (513aadcd-bf36-4115-b…beaaa79b87b:4186:13)
    at resize (513aadcd-bf36-4115-b…beaaa79b87b:12023:9)
```

**Comment by flekschas** [comment]
Oh boy. Not sure how to get to the bottom of this. There seems to be some really odd macOS-specific behavior going on in VSCode. Until I found some reliable way to get at the window size I don't know if this can be fixed. :(

**Comment by flekschas** [comment]
Just to follow up, a very simple way to reproduce the issue is to create the following anywidget in VSCode:

```py
import anywidget

class CanvasWidget(anywidget.AnyWidget):
    _esm = """
    function render({ model, el }) {
      const canvas = document.createElement("canvas");

      const resize = () => {
        canvas.height = window.innerHeight * window.devicePixelRatio;
        canvas.width = window.innerWidth * window.devicePixelRatio;
        console.log(`Canvas size is ${canvas.width} (w) x ${canvas.height} (h)`);
      }
      
      window.addEventListener('resize', resize);

      el.appendChild(canvas);
    }
    export default { render };
    """

CanvasWidget()
```

When I run this the reported canvas size is `1940 (w) x 33554426 (h)`

Look at the ridiculous height!

I've filed a ticket with VSCode to see if this is a known bug and if there's a way around this: https://github.com/microsoft/vscode/issues/225808 (Please upvote or 👍 the ticket if you want it to get traction)

**Comment by jakobtroidl** [comment]
Thanks so much for filing the vscode issue. I upvoted it and shared with other folks to upvote it as well.

**Comment by flekschas** [comment]
Woooo I think I got a fix ready!

**Comment by flekschas** [comment]
Fortunately, the reported screen dimensions are still correct so I can restrict the canvas size to be at most as large as the screen. Since no one has a screen with a display panel that's 33 million pixels tall, the rendering canvas for regl-scatterplot is limited to a reasonable size. That in turn prevents the WebGL (invalid renderbuffer size) from being thrown and everything works again!

https://github.com/user-attachments/assets/a07fb037-7273-4615-8527-20508025ceb1

**Comment by flekschas** [comment]
@jakobtroidl here's the fix: https://github.com/flekschas/jupyter-scatter/pull/149 If you have a chance, could you give it a try? To test it out, clone the repo, checkout the PR, activate hatch `hatch shell`, open VS Code `code .`, pip install from source `pip install -e .`, run the getting started notebook or the above example.

**Comment by jakobtroidl** [comment]
I just ran the `jupyter-scatter` intro example as you suggested above and I can confirm that the bug is fixed. Thanks so much @flekschas.
