### ISSUE TITLE
Incompatibility with ipywidgets v8 and jupyter-widgets v3

### ISSUE THREAD

**Issue by flekschas-ozette** [flekschas/jupyter-scatter#39]
It appears that jupyter-scatter is not working with jupyter-widgets v2 and/or v3. This is probably due to not bumping the version of `@jupyter-widgets/base` to accept v5 and v6. These jupyter versions are a complete mess...

**Comment by flekschas** [comment]
See https://github.com/jupyter-widgets/ipywidgets/issues/3607 for details.

**Comment by flekschas** [comment]
@manzt The issue might be related to the deserialization. When I run the widget with ipywidgets v8 I see the following in the console:

```
r._deserialize_state is not a function
```

Do you remember where the serialization stuff is documented?
