### ISSUE TITLE
Demo fails on load

### ISSUE THREAD

**Issue by koaning** [flekschas/jupyter-scatter#40]
When I try the tool, I keep hitting this error. 

![CleanShot 2022-10-06 at 16 47 07](https://user-images.githubusercontent.com/1019791/194344507-8e6db10f-85fc-4959-a0a8-168f56a89c68.png)

```
[Open Browser Console for more detailed log - Double click to close this message]
Model class 'JupyterScatterModel' from module 'jupyter-scatter' is loaded but can not be instantiated
TypeError: r._deserialize_state is not a function
    at f._make_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:7933)
```

Any idea what might cause it? Here are my versions: 

```
jupyter-scatter==0.7.1
jupyterlab==3.4.8
```

I'm running Python 3.9.9, should that be relevant.

**Comment by koaning** [comment]
It also persists on `jupyter-scatter=0.6.1`. I'm on an M1 Mac, should that be of influence.

**Comment by flekschas** [comment]
Thanks for testing jupyter-scatter and apologies for the glitch.

This might be related to https://github.com/flekschas/jupyter-scatter/issues/39. We recently noticed that `jupyterlab-widgets` was bumped from v1 to v3 and it seems like something internally has changed that results in jupyter-scatter not working. Do you know which version of `jupyterlab-widgets` you have installed? If it's above `v1`, would you mind downgrading to `v1` and testing jupyter-scatter again?

**Comment by koaning** [comment]
That's indeed true. Here's my versions: 

```
ipywidgets==8.0.2
jupyterlab-widgets==3.0.3
```

Will fiddle around!

**Comment by koaning** [comment]
New versions this time around: 

```
ipywidgets==8.0.2
jupyterlab-widgets==1.0.0
widgetsnbextension==4.0.3
```

This resulted in a new error. 

<img width="371" alt="CleanShot 2022-10-07 at 10 42 18@2x" src="https://user-images.githubusercontent.com/1019791/194511826-b765ebc5-4a94-499f-85ba-1271a3a6e27e.png">

**Comment by flekschas** [comment]
What is being returned when you run `jupyter labextension list`?

**Comment by koaning** [comment]
```
> jupyter labextension list
JupyterLab v3.4.7
/home/vincent/Development/spacy-vector-view/venv/share/jupyter/labextensions
        jupyter-scatter v0.7.1 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @pyviz/jupyterlab_pyviz v2.2.1 enabled OK (python, pyviz_comms)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
```

**Comment by koaning** [comment]
Maybe just as a quickfix for my end, could you share your virtualenv? Just the context of `pip freeze`? That should allow me to evaluate this project for the use-case that I have in mind, albeit just for the short term until the version issue is fixed.

**Comment by flekschas** [comment]
Apologies for responding so slowly. I was out most if the weekend. I have the following packages installed in my conda env:

```
anyio==3.5.0
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
deprecation==2.1.0
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
flake8==4.0.1
fonttools @ file:///Users/runner/miniforge3/conda-bld/fonttools_1649448536588/work
idna==3.3
iniconfig==1.1.1
ipykernel==6.9.1
ipython==8.2.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
jedi==0.18.1
Jinja2==3.1.1
json5==0.9.6
jsonschema==4.4.0
jupyter-client==7.2.2
jupyter-core==4.9.2
jupyter-packaging==0.12.0
-e git+ssh://git@github.com/flekschas/jupyter-scatter.git@b31c787615407eab4e03ffcd8a96ef98d48dd111#egg=jupyter_scatter
jupyter-scatterplot==0.1.0
jupyter-server==1.16.0
jupyterlab==3.3.3
jupyterlab-pygments==0.2.1
jupyterlab-server==2.12.0
jupyterlab-widgets==1.1.0
kiwisolver @ file:///Users/runner/miniforge3/conda-bld/kiwisolver_1648854444971/work
MarkupSafe==2.1.1
matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-suite_1639359004866/work
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
munkres==1.1.4
nbclassic==0.3.7
nbclient==0.6.0
nbconvert==6.5.0
nbformat==5.3.0
nest-asyncio==1.5.5
notebook==6.4.10
notebook-shim==0.1.0
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1649572711923/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
pandas==1.4.2
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1649818074061/work
pluggy==1.0.0
prometheus-client==0.14.1
prompt-toolkit==3.0.29
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyarrow==7.0.0
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
Pygments==2.11.2
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1649603503565/work
pyrsistent==0.18.1
pytest==7.1.2
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1647961439546/work
pyzmq==22.3.0
requests==2.27.1
Send2Trash==1.8.0
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio==1.2.0
soupsieve==2.3.2
stack-data==0.2.0
terminado==0.13.3
tinycss2==1.1.1
tomli==2.0.1
tomlkit==0.10.1
tornado @ file:///Users/runner/miniforge3/conda-bld/tornado_1648827336777/work
traitlets==5.1.1
traittypes==0.2.1
unicodedata2 @ file:///Users/runner/miniforge3/conda-bld/unicodedata2_1649111971342/work
urllib3==1.26.9
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.2
widgetsnbextension==3.6.0
```

**Comment by flekschas** [comment]
The key issue is ipywidgets and jupyterlab_widgets. For now ipywidgets `v8` and jupyterlab_widgets `v3` are not supported as they changed something internally. I created a ticket with the ipywidgets folks as it's not clear to me what causes the incompatibility: https://github.com/jupyter-widgets/ipywidgets/issues/3607

**Comment by koaning** [comment]
Could you maybe update your dependencies such that theres a maximum version of the dependencies? It's something we do a lot of in spaCy too.

**Comment by flekschas** [comment]
Makes sense! I've fixed the version of ipywidgets and jupyterlab_widgets for now (see `v0.7.3`). In my local tests it works as expected. Could you give that version a try?

**Comment by flekschas** [comment]
I fixed the incompatibilities. If you have time, can you give https://github.com/flekschas/jupyter-scatter/pull/42 a try?

**Comment by koaning** [comment]
Took me a while to get around to this, but it does now indeed seem like it works again! 

With the version-pin as the solution, I think I can close this one.
