### ISSUE TITLE
how to get selected points after linking?

### ISSUE THREAD

**Issue by chansigit** [flekschas/jupyter-scatter#43]
I found the linked plots does not supply the `.selection()` method. How can I get the selected points?

given `result=jscatter.link(list_of_scatters, );result`, I tried `result.children[0].selection()` but failed

**Comment by flekschas** [comment]
You have to do `list_of_scatters[0].selection()`

**Comment by flekschas** [comment]
`result.children[0]` is not the scatter instance. It's a VBox ipywidget instance.

**Comment by chansigit** [comment]
thank you bro!
