### ISSUE TITLE
Is there a way to get ids for selected points in the notebook?

### ISSUE THREAD

**Issue by GeorgePearse** [flekschas/jupyter-scatter#59]
This looks really excellent.

I want to be able to label an image dataset from a 2d UMAP of its embeddings, but keep struggling to find frameworks that reliably support this. Something like 

```
plot.selected_ids
```

Is that possible with this framework?

**Comment by flekschas** [comment]
I am not 100% sure what you're looking for but with jscatter it's really easy to extract the point IDs of selected points.

All you have to do is select points in the scatterplot using the lasso. Afterward you can retrieve the point IDs using `scatter.selection()`. See https://github.com/flekschas/jupyter-scatter/blob/master/API.md#scatter.selection

You can also programmatically select points via `scatter.selection(pointIds)` and zoom to selected points `scatter.zoom(scatter.selection())`

Using the selection method you can easily build your own custom annotation widget. See for instance the first 10 seconds of the video from https://twitter.com/flekschas/status/1528753226895577089. You could turn the image rendering into a widget itself that auto-updates upon changes to `scatter.selection()`. The only extra thing you'd need is likely a text input field to define a label.

Does this help?

**Comment by GeorgePearse** [comment]
This sounds perfect! Thanks a lot I basically want bulk (https://github.com/koaning/bulk), but I've found it's not scalable to my datasets.

**Comment by flekschas** [comment]
Closing this ticket now as I think the question is answered
