### ISSUE TITLE
Feature Request: Download visualizations as HTML & Javascript

### ISSUE THREAD

**Issue by murielgrobler** [flekschas/jupyter-scatter#81]
Would love to be able to download the HTML & Javascript the same way you can with `bokeh`. This way I can use the visualizations on my website!

**Comment by flekschas** [comment]
Thanks to the fabulous @manzt you can convert notebooks with jscatter to HTML using nbconvert again!  Make sure to install version `>=7.7.0` (or alternatively a version `<=6.4.4`). Then all you need to run is:

```sh
jupyter nbconvert --execute --to html notebooks/get-started.ipynb
```

Is this what you had in mind?

The view, selection, and hover synchronization unfortunately don't work yet in the HTML export but the scatter plot appear properly.

**Comment by flekschas** [comment]
I created a ticket for enabling pure JS-based view, selection, and hover linking, which will come in handy when exporting notebooks to HTML: https://github.com/flekschas/jupyter-scatter/issues/82

**Comment by flekschas** [comment]
@murielgrobler Did you have a chance to give `nbconvert` a try? I think it should do the trick.

**Comment by flekschas** [comment]
I'm closing this ticket as I think it's addressed. If you still have trouble with exporting, please reply or reopen the ticket :)

The follow up work to get linking working in the exported file is tracked via #82.
