### ISSUE TITLE
streamlit integration

### ISSUE THREAD

**Issue by arogozhnikov** [flekschas/jupyter-scatter#83]
As a suggestion: think about integrating into streamlit.

I previously used notebooks for scrnaseq and a bit for flow cytometry, but that's too problematic to share with bio folks.

Streamlit provides a better ground for 'shareable interactive visualization'. I currently use a streamlit component based on plotly (it is very scalable too, and provides just selections), but linked plots are much more responsive than my current solution.

**Comment by flekschas** [comment]
I haven't used streamlit myself yet. Does it support ipywidgets?

**Comment by arogozhnikov** [comment]
I don't think ipywidgets are supported, and issue seems to be open for a long time.

I'd recommend first just giving streamlit a try (it is very simple, and component model is also quite straightforward), and decide if this something you want in your workflow.

**Comment by flekschas** [comment]
I'm closing this ticket for now. Without ipywidget support (in particular, bidirectional communication seems to not work: https://discuss.streamlit.io/t/ipywidgets-wip/3870/14) I'd have to completely re-implement this widget for streamlit. (And maybe call it `streamlit-scatter`? 😉 ) While it could be cool to have a widget like this one for streamlit, this is outside the scope of this package as I'm focusing on the Jupyter/iPython world.
