### ISSUE TITLE
Linked plots do not show x axis

### ISSUE THREAD

**Issue by arogozhnikov** [flekschas/jupyter-scatter#84]
See this minimally modified example from get-started:

<img width="1021" alt="Screenshot 2023-07-17 at 10 20 49 PM" src="https://github.com/flekschas/jupyter-scatter/assets/6318811/ad1ab61d-5187-4f8e-ba25-d0d7e1b41a71">

**Comment by flekschas** [comment]
Apologies it took me so long. A fix is ready and shipped with the next version (`v0.14.0`) which should be live in a few minutes.
